//RobotBuilder Version: 2.0
//
//This file was generated by RobotBuilder. It contains sections of
//code that are automatically generated and assigned by robotbuilder.
//These sections will be updated in the future when you export to
//Java from RobotBuilder. Do not put any code or make any change in
//the blocks indicating autogenerated code or it will be lost on an
//update. Deleting the comments indicating the section will prevent
//it from being updated in the future.


package org.usfirst.frc.team5114.MyRobot2016.subsystems;

import java.awt.Robot;

import javax.management.timer.Timer;

import org.usfirst.frc.team5114.MyRobot2016.RobotMap;
import org.usfirst.frc.team5114.MyRobot2016.commands.*;

import edu.wpi.first.wpilibj.CANTalon;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.Servo;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;


/**
*
*/
public class BallIntake extends Subsystem {
 // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

 // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

 // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
 private final CANTalon talon6 = RobotMap.ballIntakeTalon6;
 private final DigitalInput ballSensor0 = RobotMap.intakeBallSensor0;
 private final DigitalInput ballSensor1 = RobotMap.intakeBallSensor1;
 private final Servo servo = RobotMap.ballIntakeServo;

 // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

 private double intakeSpeed = 0.5;
 private double servoPos = 0.5;
 
 // Put methods for controlling this subsystem
 // here. Call these from Commands.
 
 public double getIntakeSpeed() { return intakeSpeed; }
 public void setIntakeSpeed(double newSpeed) { intakeSpeed = newSpeed; }
 
 public void start() {
	 intakeSpeed = SmartDashboard.getNumber("Intake Speed");
	 talon6.set(intakeSpeed);
 }
 public void stop() { talon6.set(0.0); }
 
 public boolean getSwitch0() { return ballSensor0.get(); }
 public boolean switch0IsOff() { return !ballSensor0.get(); }
 public boolean getSwitch1() { return ballSensor1.get(); }
 public boolean switch1IsOff() { return !ballSensor1.get(); }
 
 public void runServo() {
	 servoPos = SmartDashboard.getNumber("Servo Pos", 0.5);
	 servo.set(1.0);
 }
 public double getServoPos() { return servoPos; }
 
 public void initDefaultCommand() {
     // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

     // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

     // Set the default command for a subsystem here.
     // setDefaultCommand(new MySpecialCommand());
 }
}