// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc.team5114.MyRobot2016;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.CANTalon;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.Servo;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	public static DigitalInput intakeBallSensor0;
	public static DigitalInput intakeBallSensor1;
	
    public static CANTalon driveTrainTalon1;
    public static CANTalon driveTrainTalon2;
    public static CANTalon driveTrainTalon3;
    public static CANTalon driveTrainTalon4;
    
    public static CANTalon ballLaunchTalon5;
    
    public static CANTalon ballIntakeTalon6;
    
    public static Servo ballIntakeServo;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    	intakeBallSensor0 = new DigitalInput(0);
        LiveWindow.addSensor("Intake", "Ball Sensor (0)", intakeBallSensor0);
        
        intakeBallSensor1 = new DigitalInput(1);
        LiveWindow.addSensor("Intake", "Ball Sensor (1)", intakeBallSensor1);
    	
        driveTrainTalon1 = new CANTalon(1);
        LiveWindow.addActuator("Drive Train", "Talon 1", driveTrainTalon1);
        
        driveTrainTalon2 = new CANTalon(2);
        LiveWindow.addActuator("Drive Train", "Talon 2", driveTrainTalon2);
        
        driveTrainTalon3 = new CANTalon(3);
        LiveWindow.addActuator("Drive Train", "Talon 3", driveTrainTalon3);
        
        driveTrainTalon4 = new CANTalon(4);
        LiveWindow.addActuator("Drive Train", "Talon 4", driveTrainTalon4);
        
        ballLaunchTalon5 = new CANTalon(5);
        LiveWindow.addActuator("Ball Launch", "Talon 5", ballLaunchTalon5);
        
        ballIntakeTalon6 = new CANTalon(6);
        LiveWindow.addActuator("Ball Intake", "Talon 6", ballIntakeTalon6);
        
        ballIntakeServo = new Servo(5);
        LiveWindow.addActuator("Ball Intake", "Servo", ballIntakeServo);
        
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
